name: Build and Check Cybersecurity Chatbot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Use your version of .NET SDK

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run basic validation
      run: dotnet format --verify-no-changes
